### ISSUE TITLE
pd.get_dummies doesn't require pd.concat!

### ISSUE THREAD

**Issue by bpshaver** [chrisalbon/notes#12]
I'm a data science instructor, and I see people doing this all the time:
```
df_sex = pd.get_dummies(df['sex'])
df_new = pd.concat([df, df_sex], axis=1)
```
This is unnecessary! You can pass the dataframe directly to the `pd.get_dummies` function and specify the columns you'd like to dummify:
```
pd.get_dummies(df, columns='sex')
```

**Comment by chrisalbon** [comment]
fixed thanks!
