### ISSUE TITLE
Naive Bayes Classifier From Scratch, "Calculate Priors"

### ISSUE THREAD

**Issue by mobatusi** [chrisalbon/notes#13]
<img width="590" alt="screen shot 2018-05-06 at 7 45 15 pm" src="https://user-images.githubusercontent.com/22042303/39679056-07ef2bd2-5166-11e8-95e0-6ddc4d795a30.png">

Thank you so much for these notes, they are very helpful. I just want to point out that In the comments you meant female, but you have male.

**Comment by chrisalbon** [comment]
fixed thanks!
