### ISSUE TITLE
404 for 'Indexing and Selecting Data With Pandas'

### ISSUE THREAD

**Issue by ptim** [chrisalbon/notes#2]
Love your work!

Heads up: https://chrisalbon.com/python/pandas_indexing_selecting.html returns a 404, (still super helpful at https://web.archive.org/web/20170107043446/https://chrisalbon.com/python/pandas_indexing_selecting.html)

Couldn't find that article in the repo...

Thanks again :)

**Comment by chrisalbon** [comment]
fixed!
