### ISSUE TITLE
Naive Bayes from scratch

### ISSUE THREAD

**Issue by birlb** [chrisalbon/notes#27]
The function:
p = 1/(np.sqrt(2*np.pi*variance_y)) * np.exp((-(x-mean_y)**2)/(2*variance_y))

keeps failing for me with 'ufunc 'subtract' did not contain a loop with signature matching types dtype('<U32') dtype('<U32') dtype('<U32')' warning. Any ideas?  Running Python 3.6.1

**Comment by chrisalbon** [comment]
no sorry/ I just reran and it works for me
