### ISSUE TITLE
DBScan Clustering - A Section's title was mentioned wrongly

### ISSUE THREAD

**Issue by jsaikmr** [chrisalbon/notes#35]
In the DBScan section, A section's title was mentioned wrongly as "Conduct Meanshift Clustering" instead of "Conduct DBScan Clustering" as highlighted in the attached below image. Kindly correct the same. Thanks

![image](https://user-images.githubusercontent.com/42650406/45406628-b72e4000-b684-11e8-8ef3-9229b0fca1bf.png)

**Comment by chrisalbon** [comment]
fixed thanks!
