### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by sarguido** [chrisalbon/notes#4]
You have a typo on this page: https://chrisalbon.com/python/data_wrangling/pandas_missing_data/ "Select some **raws**" should probably be "Select some **rows**" (see attached screenshot)
![screen shot 2018-01-19 at 12 07 42 pm](https://user-images.githubusercontent.com/3422080/35157017-727be4d0-fd11-11e7-8840-53e2b7071b7d.png)

**Comment by chrisalbon** [comment]
Nobody cares what you think

**Comment by sarguido** [comment]
This is why people don't contribute to open source. :trollface:
