### ISSUE TITLE
Bug in "Drop Highly Correlated Features"?

### ISSUE THREAD

**Issue by rochiecuevas** [chrisalbon/notes#48]
Hi Chris,

Thank you so much for publishing Python that can guide newbies like me. I'm following your code for [dropping highly correlated variables](https://chrisalbon.com/machine_learning/feature_selection/drop_highly_correlated_features/). I encountered this code, which wouldn't run, at least in my laptop:

`# Drop features` 
`df.drop(df.columns[to_drop], axis=1)`

I tried this code instead (and it seems to work fine):

`# Drop features`
`df.drop(df[to_drop], axis = 1)`

I think that deleting the __.columns__ bit allowed the script to select the columns for dropping. 

Thank you so much again!

Regards,
Rochie

**Comment by chrisalbon** [comment]
fixed!
