### ISSUE TITLE
Add conditionals to comprehensive list examples for DataFrames

### ISSUE THREAD

**Issue by vargasa** [chrisalbon/notes#52]
@chrisalbon Would be good to add conditionals to your examples with [comprehensive list with DataFrames](https://chrisalbon.com/python/data_wrangling/pandas_list_comprehension/). Something like:
```
signChanged = [
    row['A']*-1 
    if row['B'] == 'ChangeIt' else row['A']
    for index, row in data.iterrows()
]
```
Keep up the good work :+1:

**Comment by chrisalbon** [comment]
thanks!
