### ISSUE TITLE
Running StandardScaler on sparse matrix would cause the matrix to no longer be sparse

### ISSUE THREAD

**Issue by uglybachelor** [chrisalbon/notes#64]
In your article [Dimensionality Reduction On Sparse Feature Matrix](https://chrisalbon.com/machine_learning/feature_engineering/dimensionality_reduction_on_sparse_feature_matrix/). You used StandardScaler from scikit learn to standardize digit dataset. But the process would cause the matrix to be no longer sparse. I believe a better way is to use the `with_mean` parameter offered by StandardScaler(). By setting `with_mean=False`, it no longer pursuit to transform dataset to zero-mean and save the sparsity.

Cheers!

**Comment by chrisalbon** [comment]
great idea, thanks!
