### ISSUE TITLE
Tuning Neural Network Hyperparameters

### ISSUE THREAD

**Issue by rocketfish88** [chrisalbon/notes#65]
Thanks for your website and detailed and clear write-ups. I was replicating this: https://chrisalbon.com/deep_learning/keras/tuning_neural_network_hyperparameters/

and noticed not an error per se, but a warning regarding this particular code:

`grid = GridSearchCV(estimator=neural_network, param_grid=hyperparameters)`

asking that `cv` be explicitly specified as the default will shift from 3 to 5 soon.

I am curious as to what your preference for this `cv` value would be.

**Comment by chrisalbon** [comment]
fixed!
