### ISSUE TITLE
Standardize A Feature output result issue

### ISSUE THREAD

**Issue by Thomas-Wade** [chrisalbon/notes#79]
In your [Standardize A Feature](https://chrisalbon.com/machine_learning/preprocessing_structured_data/standardize_a_feature/), the output result is same with the [Rescale A Feature](https://chrisalbon.com/machine_learning/preprocessing_structured_data/rescale_a_feature/), but that's wrong.
The real result is:
array([[-1.26687088],
       [-0.39316683],
       [-0.17474081],
       [ 0.0436852 ],
       [ 1.79109332]])

**Comment by chrisalbon** [comment]
fixed!
