### ISSUE TITLE
Add one extra line at the end - some people have issues

### ISSUE THREAD

**Issue by andrewm-bose** [chrisalbon/notes#89]
Hi Chris,

Thanks for your post on how to create a remote connection to a jupyter notebook on ec2. This is awesome!

There's one extra line of code my and some friends have had to do to make it work:

sudo chown $USER:$USER /home/ubuntu/certs/mycert.pem

This should be run right before this line:
jupyter notebook

as for some people it won't work without doing this the first time.

Have an awesome day!

Andrew

**Comment by chrisalbon** [comment]
tahnks fixed!
