### ISSUE TITLE
Typo on GitHub Cheatsheet

### ISSUE THREAD

**Issue by benuklove** [chrisalbon/notes#9]
[View Unstagged Changes To Files](https://github.com/chrisalbon/notes/blob/e8da39d32cc702e22ee402a19e585772b01ed45d/content/software_engineering/cloud_computing/github_cheatsheet.md#view-unstagged-changes-to-files) has one too many g's.
:expressionless:

**Comment by chrisalbon** [comment]
fixed thanks!
